### ISSUE TITLE
GSL 2.2.1 is out...

### ISSUE THREAD

**Issue by tschoonj** [reinh-bader/fgsl#11]
... and will need support in FGSL in order to use the new features.

As far as I can tell, it is still possible to compile the current FGSL release against GSL 2.2.1, as the API was not broken.

Anyone interested in writing some code for this? I won't have time until the christmas holidays for this unfortunately....

**Comment by reinh-bader** [comment]
I've started working on the new nonlinear least squares interface and hope to complete the work within the next two weeks or so. I'll go straight for 2.3 support.

Cheers
Reinhold

**Comment by tschoonj** [comment]
Hi Reinhold,

Could you commit your work on a new branch and open a pull request for it? Every time you push a new commit to the branch, it will set off a number of builds on Travis-CI, which will test your work on multiple configurations.

Best

Tom

**Comment by reinh-bader** [comment]
Will do, but please bear with me for a few days. I'm a bit delayed due to illness of a friend. I think I should have something ready by Sunday afternoon.

**Comment by tschoonj** [comment]
No problem, there's no rush.

**Comment by reinh-bader** [comment]
first set of edits has been pushed out to the master branch. I think this should be OK, did ifort and gfortran testing locally. Unfortunately still only a small fraction of the work is done. I'll keep going on throughout the next week.

**Comment by tschoonj** [comment]
Ok, thanks!

It looks the Travis-CI build is broken. I will try and fix that this week.

**Comment by reinh-bader** [comment]
I think I am mostly done. Once CI is successful, I intend to merge into master. The only thing that appears to be not working is to refuse building against GSL < 2.3, even though there is a PCK_CHECK_MODULES entry in configure.ac.
