### ISSUE TITLE
make check -- all tests failed -- See tests/test-suite.log Please report to Reinhold.Bader@lrz.de

### ISSUE THREAD

**Issue by iurisegtovich** [reinh-bader/fgsl#17]
i ran ./configure and make under "/home/segtovichisv/Desktop/workspace-fortran+steroids/1. gsl/3. fortran fgsl/setup fgsl/fgsl-1.1.0"

.configure and make did not raise errors
make check did
by looking at test-suite.log (renamed to test-suite.log.txt in the attachment) i believe spaces in the working directory path were the problem. (i found nothing about spaces in the README)

i moved the whole dir with source and build instructions to ~/Desktop and re-ran make clean, ./configure, make and make check and then all tests passed

the error said Please report to Reinhold.Bader@lrz.de
and the site said Users of FGSL are encouraged to send bug reports via the Github ticket system.

i couldn't test on the latest release because i am testing stuff on the default "apt install *gsl*" which is the 2.1

So i guess by creating this issue, if it is not something already fixed in the latest release, some warning about spaces might be added in the README file, and maybe some next version scripts would be able to deal with spaces.

thanks for your consideration

[test-suite.log.txt](https://github.com/reinh-bader/fgsl/files/966313/test-suite.log.txt)

**Comment by tschoonj** [comment]
Thanks for bringing this up.

There is nothing we can do about this though as GNU autotools just doesn't support spaces in filenames. As a rule, I expect UNIX command line utilities to have problems dealing with spaces so I avoid using them in filenames and folder that need to be accessed or modified via the shell.

**Comment by reinh-bader** [comment]
I will add a comment in the README file. However, as Tom said, a fix for this is unlikely to happen, at least in the near future.
Regards
Reinhold
