### ISSUE TITLE
pgfortran issue -- failed to compile -- two tests failed

### ISSUE THREAD

**Issue by neffw** [reinh-bader/fgsl#18]
I tried to compile FGSL with PGI's fortran compiler and got the following error messages:
```
PGF90-S-0034-Syntax error at or near VALUE (./interface/ode.finc: 141)
PGF90-S-0034-Syntax error at or near VALUE (./interface/spmatrix.finc: 61)
  0 inform,   0 warnings,   2 severes, 0 fatal for fgsl
```
Apparently pgfortran does not like `value` statements. After replacing the statements by attributes the code compiled but two tests failed:
```
FAIL: spmatrix
FAIL: splinalg
``` 
There are also two XFAILs but I think they are expected:
```
XFAIL: error
XFAIL: error_1
```
Please refer to the attached files for details.

- [fgsl-pgi.txt](https://github.com/reinh-bader/fgsl/files/981040/fgsl-pgi.txt)
- [error.txt](https://github.com/reinh-bader/fgsl/files/981036/error.txt)
- [error_1.txt](https://github.com/reinh-bader/fgsl/files/981035/error_1.txt)
- [splinalg.txt](https://github.com/reinh-bader/fgsl/files/981034/splinalg.txt)
- [spmatrix.txt](https://github.com/reinh-bader/fgsl/files/981033/spmatrix.txt)

**Comment by tschoonj** [comment]
Looks like a compiler bug to me. Did you use the latest version of this compiler?

**Comment by neffw** [comment]
You are right, tschoonj. I installed the brand-new pgfortran 17.4 released just a few days ago. It accepts the value statement and the errors are gone. Thanks for the fast reply.

**Comment by neffw** [comment]
You are right, tschoonj. I installed the brand-new pgfortran 17.4 released just a few days ago. It accepts the value statement and the errors are gone. Thanks for the fast reply.
