### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by yosshee** [reinh-bader/fgsl#23]
Hello. I'm a beginner for programing.
I installed fgsl through Macbrew. And I made a file with "use fgsl".
But I can't compile it.
How do you compile using gfortran.
Please tell me ....

**Comment by tschoonj** [comment]
It should be as simple as:

````
gfortran -o myprog `pkg-config --cflags fgsl` myprog.f90 `pkg-config --libs fgsl`
````

assuming your source file is called `myprog.f90`.
