### ISSUE TITLE
FGSL fails to build against GSL >2.0

### ISSUE THREAD

**Issue by tanderson92** [reinh-bader/fgsl#3]
The following error occurs when building against recent GSL versions:
make -j3 -j1
make all-recursive
make[1]: Entering directory '/var/tmp/paludis/build/sci-libs-fgsl-1.0.0-r1/work/fgsl-1.0.0'
Making all in .
make[2]: Entering directory '/var/tmp/paludis/build/sci-libs-fgsl-1.0.0-r1/work/fgsl-1.0.0'
/bin/sh ./libtool --tag=FC --mode=compile x86_64-pc-linux-gnu-gfortran -DHAVE_CONFIG_H -I. -I. -I. -pipe -O2 -march=native -g -O2 -c -o fgsl.lo fgsl.F90
libtool: compile: x86_64-pc-linux-gnu-gfortran -DHAVE_CONFIG_H -I. -I. -I. -pipe -O2 -march=native -g -O2 -c fgsl.F90 -fPIC -o .libs/fgsl.o
libtool: compile: x86_64-pc-linux-gnu-gfortran -DHAVE_CONFIG_H -I. -I. -I. -pipe -O2 -march=native -g -O2 -c fgsl.F90 -o fgsl.o >/dev/null 2>&1
/bin/sh ./libtool --tag=CC --mode=compile x86_64-pc-linux-gnu-cc -DHAVE_CONFIG_H -I. -I. -I. -pipe -O2 -march=native -pipe -O2 -march=native -c -o libfgsl_la-fgsl_utils.lo test -f 'fgsl_utils.c' || echo './'fgsl_utils.c
libtool: compile: x86_64-pc-linux-gnu-cc -DHAVE_CONFIG_H -I. -I. -I. -pipe -O2 -march=native -pipe -O2 -march=native -c fgsl_utils.c -fPIC -DPIC -o .libs/libfgsl_la-fgsl_utils.o
fgsl_utils.c:1090:13: error: conflicting types for 'gsl_multifit_fdfsolver_jac'
gsl_matrix gsl_multifit_fdfsolver_jac(gsl_multifit_fdfsolver s) {
^
In file included from fgsl_utils.c:21:0:
/usr/x86_64-pc-linux-gnu/include/gsl/gsl_multifit_nlin.h:177:5: note: previous declaration of 'gsl_multifit_fdfsolver_jac' was here
int gsl_multifit_fdfsolver_jac (gsl_multifit_fdfsolver * s,
^
fgsl_utils.c: In function 'gsl_multifit_fdfsolver_jac':
fgsl_utils.c:1091:13: error: 'gsl_multifit_fdfsolver' has no member named 'J'
return s->J;
^
Makefile:397: recipe for target 'libfgsl_la-fgsl_utils.lo' failed
make[2]: [libfgsl_la-fgsl_utils.lo] Error 1
make[2]: Leaving directory '/var/tmp/paludis/build/sci-libs-fgsl-1.0.0-r1/work/fgsl-1.0.0'
Makefile:449: recipe for target 'all-recursive' failed
make[1]: [all-recursive] Error 1
make[1]: Leaving directory '/var/tmp/paludis/build/sci-libs-fgsl-1.0.0-r1/work/fgsl-1.0.0'
Makefile:266: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by etempel** [comment]
I noticed the same error. Hopefully it will be corrected in near future.

**Comment by tschoonj** [comment]
We are aware of this. I will work on this over the next six weeks

**Comment by tschoonj** [comment]
Work is progressing nicely. Check out my [gsl-2](https://github.com/tschoonj/fgsl/tree/gsl-2) branch if you want to give it a try.

**Comment by tanderson92** [comment]
Works great here. Thanks for the work. Let me know if you would like any further testing before a merge.

**Comment by tschoonj** [comment]
Branch has been merged in now.
