### ISSUE TITLE
Issue when compiling an example program 

### ISSUE THREAD

**Issue by sara-phoo** [reinh-bader/fgsl#31]
Hello,
I copied and paste the example program  multiroot.f90. I tried to compile it using 
gfortran -I/usr/local/include/fgsl -I/home/sara/fgsl_build/tests prova_multiroot.f -lfgsl -lgsl -lgslcblas -lm but i get the following message /tmp/cccwLMcu.o: In function `MAIN__':
prova_multiroot.f:(.text+0x676): undefined reference to `__mod_unit_MOD_unit_init'
prova_multiroot.f:(.text+0x7e5): undefined reference to `__mod_unit_MOD_unit_assert_equal_string'
prova_multiroot.f:(.text+0x8e2): undefined reference to `__mod_unit_MOD_unit_assert_equal_integer'
prova_multiroot.f:(.text+0x96d): undefined reference to `__mod_unit_MOD_unit_assert_true'
prova_multiroot.f:(.text+0xb5c): undefined reference to `__mod_unit_MOD_unit_assert_equal_integer'
prova_multiroot.f:(.text+0xbc4): undefined reference to `__mod_unit_MOD_unit_assert_equal_within_double_array'
prova_multiroot.f:(.text+0xd47): undefined reference to `__mod_unit_MOD_unit_assert_equal_string'
prova_multiroot.f:(.text+0xe51): undefined reference to `__mod_unit_MOD_unit_assert_equal_integer'
prova_multiroot.f:(.text+0xedc): undefined reference to `__mod_unit_MOD_unit_assert_true'
prova_multiroot.f:(.text+0x10cb): undefined reference to `__mod_unit_MOD_unit_assert_equal_integer'
prova_multiroot.f:(.text+0x1133): undefined reference to `__mod_unit_MOD_unit_assert_equal_within_double_array'
prova_multiroot.f:(.text+0x114c): undefined reference to `__mod_unit_MOD_unit_finalize'
collect2: error: ld returned 1 exit status
Can you help me?

ps: removing the instruction I/home/sara/fgsl_build/tests, that is the the path wher I found  mod_unit.mod, I got   use mod_unit
         1
Fatal Error: Can't open module file ‘mod_unit.mod’ for reading at (1): No such file or directory
compilation terminated.
  

Thank you in advance, 
Sara

**Comment by reinh-bader** [comment]
The program is from the unit tests, so you would also need to copy mod_unit.f90, and compile that in advance. Also, you need to add the generated .o object file to your linkage line.

Regards
Reinhold

**Comment by sara-phoo** [comment]
Thank you. Now the program is compiling and it runs. 
Refards,

Sara

**Comment by reinh-bader** [comment]
Good! Closing the issue hereby.
