### ISSUE TITLE
[Package Manage] fgsl to support fpm?

### ISSUE THREAD

**Issue by zoziha** [reinh-bader/fgsl#32]
Hello, is it possible for `fgsl` to support [fortran-lang/fpm](https://github.com/fortran-lang/fpm), which is a package manager and build system for Fortran?
(Also see https://github.com/fortran-lang/fpm/issues/445)

**Comment by tschoonj** [comment]
Feel free to open a pull request that adds support for `fpm` and it will be reviewed.

**Comment by reinh-bader** [comment]
I suggest to close this issue since there was no further response. Note that I hear that fpm may have technical difficulties with mixed-language setups, at least at its current state of development.

**Comment by zoziha** [comment]
Indeed, technically, fpm is currently unable to support gsl's mixed-language programming. Agreed to close this issue.

**Comment by reinh-bader** [comment]
Closed as unresolvable.
