### ISSUE TITLE
CPU usage issue

### ISSUE THREAD

**Issue by OakleyYoung** [reinh-bader/fgsl#35]
Hello, I am trying to use the fgsl linear algebra solver. I am running into issues with CPU usage when I run my program. I have used the example docs on your page to make the Fortran script linked below. 
Issue: When I uncomment to solver section in the main script (lines 104 to 116 in main.F90) and run the program the CPU usage reaches astronomical levels! I am using “fgsl_splinalg_itersolve_iterate()”  to solve the equation Au=f, where A is a 25920 by 25920 matrix and both u and f are 25920 length vectors. This equation is solved for each time step. I was just wondering if anyone else experienced similar issues with CPU usage when using fgsl/ is there a fix?
Minimal reproducible example found at: https://github.com/exoclim/ulmo/tree/main/MRE_fgsl/src

**Comment by tschoonj** [comment]
That's a pretty big matrix so I am not surprised it eats into your CPU usage.

FGSL is really just a thin wrapper around GSL, so any performance issues will be due to the underlying GSL methods that are being called. You can confirm this by rewriting your program into C and use GSL directly.

**Comment by OakleyYoung** [comment]
Thank you for the quick response! Sorry, I should have said that the CPU usage is over multiple CPUs. I have run the same program in c and it uses 100% of 1 CPU, but when I write the same code in Fortran with fgsl it starts using nearly 100% of multiple CPUs.

**Comment by tschoonj** [comment]
Oh I understand now. 

You seem to be using a [for](https://github.com/exoclim/ulmo/blob/6d2c552ec7f3b1d67781694216143f950c7426b6/MRE_fgsl/src/main.F90#L96) loop in your Fortran code that calls `fgsl_splinalg_itersolve_iterate `. Given that the top-level for loop iterations look independent to me, perhaps the Fortran compiler parallellized them out? Did you use some aggressive optimisation option while compiling? Perhaps try with all optimisations turned off (`-O0`) and see if the multithreading persists.

Either way, I am not convinced that FGSL could be responsible for this.

**Comment by OakleyYoung** [comment]
Thank you! Unfortunately turning off the optimizations seems to not work either. I am going to do a bit of research and see if other FORTRAN flags could be anyway related to multi-threading. Again thanks so much for the help and quick responses. Hopefully, I will be able to get it working!

**Comment by reinh-bader** [comment]
I am closing this issue as not directly related to the FGSL implementation.

**Comment by reinh-bader** [comment]
Question on usage was answered.
