### ISSUE TITLE
Compilation failure with GSL 2.1

### ISSUE THREAD

**Issue by fmeynadier** [reinh-bader/fgsl#8]
Hello,

I get the following error on compilation : 
<code>
gfortran -DHAVE_CONFIG_H -I.  -I. -I.   -g -O2 -c -o fgsl.o fgsl.F90
api/spmatrix.finc:75.36:
    Included at fgsl.F90:1939:

  call gsl_spmatrix_cumsum(n, c_loc(c))
                                    1
Error: Assumed-shape array 'c' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/fit.finc:47.39:
    Included at fgsl.F90:1934:

    fgsl_fit_wmul = gsl_fit_wmul(c_loc(x), xstride, c_loc(w), wstride, &
                                       1
Error: Assumed-shape array 'x' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/fit.finc:38.37:
    Included at fgsl.F90:1934:

    fgsl_fit_mul = gsl_fit_mul(c_loc(x), xstride, c_loc(y), ystride, n, c1, &
                                     1
Error: Assumed-shape array 'x' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/fit.finc:23.45:
    Included at fgsl.F90:1934:

    fgsl_fit_wlinear = gsl_fit_wlinear(c_loc(x), xstride, c_loc(w), wstride, &
                                             1
Error: Assumed-shape array 'x' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/fit.finc:14.43:
    Included at fgsl.F90:1934:

    fgsl_fit_linear = gsl_fit_linear(c_loc(x), xstride, c_loc(y), ystride, n, c
                                           1
Error: Assumed-shape array 'x' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/dht.finc:34.52:
    Included at fgsl.F90:1929:

    fgsl_dht_apply = gsl_dht_apply(t%gsl_dht, c_loc(f_in), c_loc(f_out))
                                                    1
Error: Assumed-shape array 'f_in' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/wavelet.finc:156.64:
    Included at fgsl.F90:1928:

         gsl_wavelet2d_nstransform_inverse(w%gsl_wavelet, c_loc(data), &
                                                                1
Error: Assumed-shape array 'data' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/wavelet.finc:146.64:
    Included at fgsl.F90:1928:

         gsl_wavelet2d_nstransform_forward(w%gsl_wavelet, c_loc(data), &
                                                                1
Error: Assumed-shape array 'data' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/wavelet.finc:136.80:
    Included at fgsl.F90:1928:

gsl_wavelet2d_nstransform = gsl_wavelet2d_nstransform(w%gsl_wavelet, c_loc(data
                                                                           1
Error: Assumed-shape array 'data' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/wavelet.finc:98.62:
    Included at fgsl.F90:1928:

         gsl_wavelet2d_transform_inverse(w%gsl_wavelet, c_loc(data), &
                                                              1
Error: Assumed-shape array 'data' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/wavelet.finc:88.62:
    Included at fgsl.F90:1928:

         gsl_wavelet2d_transform_forward(w%gsl_wavelet, c_loc(data), &
                                                              1
Error: Assumed-shape array 'data' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/wavelet.finc:78.76:
    Included at fgsl.F90:1928:

   fgsl_wavelet2d_transform = gsl_wavelet2d_transform(w%gsl_wavelet, c_loc(data
                                                                           1
Error: Assumed-shape array 'data' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/wavelet.finc:68.88:
    Included at fgsl.F90:1928:

let_transform_inverse = gsl_wavelet_transform_inverse(w%gsl_wavelet, c_loc(data
                                                                           1
Error: Assumed-shape array 'data' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/wavelet.finc:59.88:
    Included at fgsl.F90:1928:

let_transform_forward = gsl_wavelet_transform_forward(w%gsl_wavelet, c_loc(data
                                                                           1
Error: Assumed-shape array 'data' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/wavelet.finc:50.72:
    Included at fgsl.F90:1928:

    fgsl_wavelet_transform = gsl_wavelet_transform(w%gsl_wavelet, c_loc(data), &
                                                                        1
Error: Assumed-shape array 'data' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/ode.finc:547.25:
    Included at fgsl.F90:1924:

         t, t1, h, c_loc(y))
                         1
Error: Assumed-shape array 'y' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/ode.finc:519.15:
    Included at fgsl.F90:1924:

         c_loc(y0), c_loc(yerr), c_loc(dydt), c_loc(h))
               1
Error: Assumed-shape array 'y0' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/ode.finc:491.15:
    Included at fgsl.F90:1924:

         c_loc(scale_abs), size(scale_abs, kind=fgsl_size_t))
               1
Error: Assumed-shape array 'scale_abs' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/ode.finc:464.10:
    Included at fgsl.F90:1924:

    c_loc(y), c_loc(yerr), &
          1
Error: Assumed-shape array 'y' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/ode.finc:219.46:
    Included at fgsl.F90:1924:

         dydt%gsl_odeiv2_system, t, h0, c_loc(y))
                                              1
Error: Assumed-shape array 'y' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/ode.finc:206.25:
    Included at fgsl.F90:1924:

         t, t1, h, c_loc(y))
                         1
Error: Assumed-shape array 'y' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/ode.finc:163.56:
    Included at fgsl.F90:1924:

         c%gsl_odeiv2_control, s%gsl_odeiv2_step, c_loc(y), c_loc(yerr), c_loc(
                                                        1
Error: Assumed-shape array 'y' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/ode.finc:128.15:
    Included at fgsl.F90:1924:

         c_loc(scale_abs), size(scale_abs, kind=fgsl_size_t))
               1
Error: Assumed-shape array 'scale_abs' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/ode.finc:102.10:
    Included at fgsl.F90:1924:

    c_loc(y), c_loc(yerr), c_loc(dydt_in), c_loc(dydt_out), dydt%gsl_odeiv2_sys
          1
Error: Assumed-shape array 'y' at (1) cannot be an argument to the procedure 'c_loc' because it is not C interoperable
api/ntuple.finc:33.34:
    Included at fgsl.F90:1921:

            gsl_ntuple_open(c_loc(lname), data, size)
                                  1
Error: CHARACTER argument 'lname' to 'c_loc' at (1) must have a length of 1
Fatal Error: Error count reached limit of 25.
make: *** [fgsl.o] Erreur 1
</code>

I tried with both the latest stable release (1.1.0) and the git master, same error.

gsl is version 2.1, compiled from the sources.

Please let me know if any other information is useful...

**Comment by tschoonj** [comment]
What version is your gfortran compiler?

**Comment by fmeynadier** [comment]
<code>
$ gfortran -v
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1) 
</code>

(i.e., the packaged version for ubuntu 14.04)

**Comment by tschoonj** [comment]
Ok, thanks for the information, I will look into it soon

**Comment by fmeynadier** [comment]
Many thanks for that !

**Comment by tschoonj** [comment]
I think the compiler does not support the Fortran 2003 feature that was used here. [It seems ](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=50269) that it was only added in gcc 4.9.

I will run some tests with different gcc versions to confirm.

**Comment by reinh-bader** [comment]
Actually, the feature needed here is not in Fortran 2003. The rules on what c_loc can take were relaxed in TS 29113 (already integrated into the Fortran 2015 draft). From a conformance view, the FGSL code is then fine as long as the actual argument is contiguous. To enforce this, it may be appropriate to add the CONTIGUOUS attribute to the assumed shape array declarations, but this again presupposes that gfortran supports the attribute (i. e. performs copy-in/out for non-contiguous actuals).

Regards
Reinhold

**Comment by tschoonj** [comment]
`CONTIGUOUS` doesn't appear to have an effect here. I still get the same error about the assumed shaped array not being C-interoperable.

We could of course just update the configure.ac script with a fortran compiler test for this feature, and do not allow compilers that fail the test.

**Comment by reinh-bader** [comment]
CONTIGUOUS indeed wouldn't fix any problem with c_loc. It would only make the interfaces more reliable. (The original code used assumed size arrays, which would cause copy-in/out automatically if a non-contiguous actual argument is supplied).

I agree that you will need to constrain to using compilers that do allow assumed shape.

Cheers
Reinhold

**Comment by tschoonj** [comment]
The feature that I implemented here: is it Fortran 2008 or Fortran 2015?

**Comment by reinh-bader** [comment]
It is, actually, Fortran 2008. Sorry for the incorrect info I gave earlier. The TS added further features, but permitting a contiguous assumed shape array was already added in 2008.

**Comment by fmeynadier** [comment]
Many thanks for those findings !

On my side, I simply downgraded gsl 2.1 to 1.16 (went back to the ubuntu package), and compiled fsgl 1.0.0 with that.

I'll be looking forward to installing gsl 2.1 / fgsl 1.1.0 as soon as gcc gets upgraded (16.04 LTS is only a few days away, but I don't know yet if (and when) I'll switch this system).
Thanks again, for making fgsl.

Best regards,

-- 
 Frédéric

**Comment by tschoonj** [comment]
By the way there is no need to compile fgsl on Ubuntu 14.04: I have made deb packages for it already.

Instructions can be found [here](http://www.lrz.de/services/software/mathematik/gsl/fortran/)
